In [25]:
from itertools import product
from itertools import combinations
import numpy as np

In [40]:
n_feature = 4
concept_basis = []
gen_concept = product([0,1], repeat=n_feature)
for concept in gen_concept:
    concept_basis.append(np.array(concept))

In [41]:
n_feature = len(concept_basis[0])

In [44]:
n = 10
basis_size = 2**n_feature
concept_space = np.zeros([n, n_feature])
perm = np.random.permutation(basis_size)[0:n]

In [45]:
perm

array([10,  5, 12,  3,  2,  0,  8, 15, 13,  4])

In [46]:
for ind, val in enumerate(perm):
    concept_space[ind,:] = concept_basis[val]

In [49]:
concept_space

array([[1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 1., 0., 0.],
       [0., 0., 1., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 0., 1.],
       [0., 1., 0., 0.]])

In [68]:
n_concept, n_feature = concept_space.shape
n_y = 2
likelihood = np.zeros([n_concept, n_feature, n_y])
likelihood[:,:,0] = 1 - concept_space 
likelihood[:,:,1] = concept_space

In [76]:
xs = [0,2,1]
ys = [1,1,1]

In [78]:
np.product(likelihood[0,xs,ys])

0.0

In [84]:
0*np.log(0)

/Users/CoDaS/anaconda3/envs/py35/lib/python3.5/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in log
  if __name__ == '__main__':
/Users/CoDaS/anaconda3/envs/py35/lib/python3.5/site-packages/ipykernel/__main__.py:1: RuntimeWarning: invalid value encountered in double_scalars
  if __name__ == '__main__':


nan

In [87]:
a = np.arange(10)
a = a/np.sum(a)

In [91]:
-np.nansum(a*np.log(a))

/Users/CoDaS/anaconda3/envs/py35/lib/python3.5/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in log
  if __name__ == '__main__':
/Users/CoDaS/anaconda3/envs/py35/lib/python3.5/site-packages/ipykernel/__main__.py:1: RuntimeWarning: invalid value encountered in multiply
  if __name__ == '__main__':


2.0498407203926647

In [ ]:
n_obs = len(xs)
n_concept, n_feature, ny = likelihood.shape
posterior = np.zeros(n_concept)
for i in range(n_concept):
    lik_factors = np.zeros(n_obs)
    

In [119]:
a = np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [120]:
b = np.array([1,2])
c = np.repeat(b, [3,4], axis=0)
c

array([1, 1, 1, 2, 2, 2, 2])

In [122]:
np.sum(a*a, axis=0)

array([[144, 170, 200, 234],
       [272, 314, 360, 410],
       [464, 522, 584, 650]])

In [123]:
np.array([1]*4)

array([1, 1, 1, 1])

In [124]:
a/a

/Users/CoDaS/anaconda3/envs/py35/lib/python3.5/site-packages/ipykernel/__main__.py:1: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':


array([[[nan,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]]])

In [125]:
a.argmax()

23

In [126]:
np.random.random(10)

array([0.55729017, 0.47925984, 0.47695377, 0.03299641, 0.43367019,
       0.33207688, 0.82822563, 0.59878073, 0.08293795, 0.82912123])

In [130]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [128]:
a[:,[1,0]]

array([[2, 1],
       [4, 3]])

In [131]:
a[[1,0],:]

array([[3, 4],
       [1, 2]])

In [134]:
for i in range(2,5):
    print(i)

2
3
4


In [135]:
a = np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [136]:
a.max(axis=0)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [138]:
b = np.array([[0,1],[2,3]])
b.flatten()

array([0, 1, 2, 3])

In [139]:
np.random.randn(10)

array([-0.30409053,  0.54897453, -0.65295357,  1.52244454,  0.9683736 ,
        0.49913174, -0.79022669,  0.58650912, -0.51928625,  1.66713641])

In [144]:
basis_size = 2**4
from scipy.special import comb
k = np.arange(2, basis_size+1)
n = np.array([basis_size]*(basis_size-1))
vec = comb(n, k, exact=False)
print(vec)
print(np.sum(vec))

[1.200e+02 5.600e+02 1.820e+03 4.368e+03 8.008e+03 1.144e+04 1.287e+04
 1.144e+04 8.008e+03 4.368e+03 1.820e+03 5.600e+02 1.200e+02 1.600e+01
 1.000e+00]
65519.0


In [153]:
from scipy.stats import dirichlet
quantiles = np.array([0.25, 0.25, 0.25, 0.25])  # specify quantiles
alpha = np.array([1, 1, 1, 2])  # specify concentration parameters
dirichlet.pdf(quantiles, alpha)

6.000000000000001