In [99]:
%reload_ext autoreload
%autoreload 2

from concept import concept_basis
from graph_active_learning_sy import *

from dag import DirectedGraph
from graph_utils import create_graph_hyp_space
from graph_utils import create_active_learning_hyp_space
from graph_utils import create_teaching_hyp_space
from graph_active_learner import GraphActiveLearner
from graph_self_teacher import GraphSelfTeacher

from itertools import combinations
from itertools import permutations

import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

In [72]:
active_graph_space = create_active_learning_hyp_space(t=0.8, b=0.0)

In [73]:
print(len(active_graph_space))

27


In [39]:
ag = GraphActiveLearner(active_graph_space[1])

ag.update_posterior()
print('Step 1')
print('Prior:')
print(ag.prior)
print('Posterior:')
print(ag.posterior)
print('Prior entropy:')
print(ag.prior_entropy())
print('Posterior entropy:')
print(ag.posterior_entropy())
print('EIG')
print(ag.expected_information_gain())
print('\n')

ag.prior = ag.posterior
ag.update_posterior()
print('Step 2')
print('Prior:')
print(ag.prior)
print('Posterior:')
print(ag.posterior)
print('Prior entropy:')
print(ag.prior_entropy())
print('Posterior entropy:')
print(ag.posterior_entropy())
print('EIG')
print(ag.expected_information_gain())
print('\n')

ag.prior = ag.posterior
ag.update_posterior()
print('Step 3')
print('Prior:')
print(ag.prior)
print('Posterior:')
print(ag.posterior)
print('Prior entropy:')
print(ag.prior_entropy())
print('Posterior entropy:')
print(ag.posterior_entropy())
print('EIG')
print(ag.expected_information_gain())
print('\n')

Step 1
Prior:
[[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]]
Posterior:
[[0.83333333 0.         0.         0.         0.03846154 1.
  0.83333333 0.         1.         1.         0.         0.        ]
 [0.16666667 0.         1.         0.         0.96153846 0.
  0.16666667 1.         0.         0.         0.         0.        ]]
Prior entropy:
[1. 1. 1.]
Posterior entropy:
[0.65002242 0.         0.         0.         0.23519338 0.
 0.65002242 0.         0.         0.         0.         0.        ]
EIG
[0.29079207 0.41841585 0.29079207]


Step 2
Prior:
[[0.83333333 0.         0.         0.         0.03846154 1.
  0.83333333 0.         1.         1.         0.         0.        ]
 [0.16666667 0.         1.         0.         0.96153846 0.
  0.16666667 1.         0.         0.         0.         0.        ]]
Posterior:
[[0.96153846 0.         0.         0.         0.00159744 1.
  0.96153846 0.         1.         1.         0.        

/Users/CoDaS/Dropbox/ShaftoLab/is-it-optimal/causal_graph/graph_active_learner.py:63: RuntimeWarning: divide by zero encountered in true_divide
  prior_entropy = np.nansum(self.prior * np.log2(1/self.prior), axis=0)
/Users/CoDaS/Dropbox/ShaftoLab/is-it-optimal/causal_graph/graph_active_learner.py:63: RuntimeWarning: invalid value encountered in multiply
  prior_entropy = np.nansum(self.prior * np.log2(1/self.prior), axis=0)


In [89]:
stg = GraphSelfTeacher(active_graph_space[0])
stg.update_learner_posterior()

lik = stg.likelihood()
print('Likelihood:')
print(lik)

post_l = stg.learner_posterior
print('Learner posterior:')
print(post_l)

post_t = stg.update_self_teaching_posterior()
print('Self teacher posterior:')
print(post_t)

Likelihood:
[[1.   0.   0.   0.   0.04 0.16 1.   0.   0.16 0.64 0.   0.  ]
 [0.04 0.16 0.16 0.64 1.   0.   1.   0.   0.   0.   0.   0.  ]]
Learner posterior:
[[0.96153846 0.         0.         0.         0.03846154 1.
  0.5        0.         1.         1.         0.         0.        ]
 [0.03846154 1.         1.         1.         0.96153846 0.
  0.5        0.         0.         0.         0.         0.        ]]
Self teacher posterior:
[0.44444444 0.44444444 0.11111111]


In [5]:
obs_basis = concept_basis(3)
for i in range(len(obs_basis)):
    print(obs_basis[i])

[0 0 0]
[0 0 1]
[0 1 0]
[0 1 1]
[1 0 0]
[1 0 1]
[1 1 0]
[1 1 1]


In [41]:
# 8 possible observations
obs_poss = [[0, 0, 0],
[0, 0, 1],
[0, 1, 0],
[0, 1, 1],
[1, 0, 0],
[1, 0, 1],
[1, 1, 0],
[1, 1, 1]]

# Wai Keen's 12 observations
# 0 = intervene, 1 = observed_off, 2 = observed_on
wk_obs = [[0, 1, 1], 
[0, 1, 2], 
[0, 2, 1], 
[0, 2, 2], 
[1, 0, 1], 
[1, 0, 2], 
[1, 1, 0], 
[1, 2, 0], 
[2, 0, 1], 
[2, 0, 2], 
[2, 1, 0], 
[2, 2, 0]]

x_list = [0,0,0,0,1,1,2,2,1,1,2,2]

# transform the above to observations
wk_trans = [[1, 0, 0],
[1, 0, 1],
[1, 1, 0],
[1, 1, 1],
[0, 1, 0],
[0, 1, 1],
[0, 0, 1],
[0, 1, 1],
[1, 1, 0],
[1, 1, 1],
[1, 0, 1],
[1, 1, 1]]

In [42]:
tmp = np.array(wk_obs)
tmp[tmp!=1] = -1
tmp[tmp==1] = 0
tmp[tmp==-1] = 1
tmp

array([[1, 0, 0],
       [1, 0, 1],
       [1, 1, 0],
       [1, 1, 1],
       [0, 1, 0],
       [0, 1, 1],
       [0, 0, 1],
       [0, 1, 1],
       [1, 1, 0],
       [1, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [44]:
y_list = []
for item in wk_trans:
    for ind, obs in enumerate(obs_poss):
        if np.array_equal(item, obs):
            y_list.append(ind)
            print("{} --> {}".format(item, ind))

[1, 0, 0] --> 4
[1, 0, 1] --> 5
[1, 1, 0] --> 6
[1, 1, 1] --> 7
[0, 1, 0] --> 2
[0, 1, 1] --> 3
[0, 0, 1] --> 1
[0, 1, 1] --> 3
[1, 1, 0] --> 6
[1, 1, 1] --> 7
[1, 0, 1] --> 5
[1, 1, 1] --> 7


In [45]:
print(x_list)
print(y_list)

[0, 0, 0, 0, 1, 1, 2, 2, 1, 1, 2, 2]
[4, 5, 6, 7, 2, 3, 1, 3, 6, 7, 5, 7]


In [17]:
# each of the 12 in Wai Keen's observation list 
# should map onto two indices in my obserbation list (x, obs)
[1, 0, 0] --> 0,4
[1, 0, 1] --> 0,5
[1, 1, 0] --> 0,6
[1, 1, 1] --> 0,7
[0, 1, 0] --> 1,2
[0, 1, 1] --> 1,3
[0, 0, 1] --> 2,1
[0, 1, 1] --> 2,3
[1, 1, 0] --> 1,6
[1, 1, 1] --> 1,7
[1, 0, 1] --> 2,5
[1, 1, 1] --> 2,7

array([[1, 0, 0],
       [1, 0, 1],
       [1, 1, 0],
       [1, 1, 1],
       [0, 1, 0],
       [0, 1, 1],
       [0, 0, 1],
       [0, 1, 1],
       [1, 1, 0],
       [1, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [54]:
graph_spaces = create_graph_hyp_space(t=0.8, b=0)

In [56]:
graph_spaces['common_cause_2'].likelihood()

[1.0,
 0.0,
 0.0,
 0.0,
 0.03999999999999998,
 0.15999999999999998,
 1.0,
 0.0,
 0.15999999999999998,
 0.6400000000000001,
 0.0,
 0.0]

In [63]:
wk_prob = np.array([graph_spaces['common_cause_2'].likelihood(), graph_spaces['common_cause_1'].likelihood()])

In [92]:
# transform Wai Keen's likelihood format to my likelihood format
def wk2sy_full_prob(wk_prob):
    n_concept = 2
    n_feature = 3
    n_obs = 8
    sy_prob = np.zeros([n_concept, n_feature, n_obs])
    for i, concept in enumerate(wk_prob):
        sy_prob[i,0,4] = wk_prob[i,0]
        sy_prob[i,0,5] = wk_prob[i,1]
        sy_prob[i,0,6] = wk_prob[i,2]
        sy_prob[i,0,7] = wk_prob[i,3]
        sy_prob[i,1,2] = wk_prob[i,4]
        sy_prob[i,1,3] = wk_prob[i,5]
        sy_prob[i,2,1] = wk_prob[i,6]
        sy_prob[i,2,3] = wk_prob[i,7]
        sy_prob[i,1,6] = wk_prob[i,8]
        sy_prob[i,1,7] = wk_prob[i,9]
        sy_prob[i,2,5] = wk_prob[i,10]
        sy_prob[i,2,7] = wk_prob[i,11]
    return sy_prob

In [66]:
sy_prob

array([[[0.  , 0.  , 0.  , 0.  , 1.  , 0.  , 0.  , 0.  ],
        [0.  , 0.  , 0.04, 0.16, 0.  , 0.  , 0.16, 0.64],
        [0.  , 1.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ]],

       [[0.  , 0.  , 0.  , 0.  , 0.04, 0.16, 0.16, 0.64],
        [0.  , 0.  , 1.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
        [0.  , 1.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ]]])

In [70]:
prior = np.array([0.5, 0.5])
eig = expected_information_gain(sy_prob, prior)
eig = normalize(eig)
eig

/Users/CoDaS/Dropbox/ShaftoLab/is-it-optimal/util.py:19: RuntimeWarning: divide by zero encountered in log
  return -np.nansum(vec*np.log(vec))
/Users/CoDaS/Dropbox/ShaftoLab/is-it-optimal/util.py:19: RuntimeWarning: invalid value encountered in multiply
  return -np.nansum(vec*np.log(vec))


array([0.5, 0.5, 0. ])

In [97]:
# Check that WK's and SY's EIG is the same
for space in active_graph_space:
    ag = GraphActiveLearner(space)
    ag.update_posterior()
    print("WK's EIG: {}".format(ag.expected_information_gain()))
    lik = wk2sy_full_prob(ag.likelihood())
    # print(lik.shape)
    prior = np.array([0.5, 0.5])
    eig = expected_information_gain(lik, prior)
    print("SY's EIG: {}".format(normalize(eig)))
    print("")

WK's EIG: [0.5 0.5 0. ]
SY's EIG: [0.5 0.5 0. ]

WK's EIG: [0.29079207 0.41841585 0.29079207]
SY's EIG: [0.29079207 0.41841585 0.29079207]

WK's EIG: [0.5 0.5 0. ]
SY's EIG: [0.5 0.5 0. ]

WK's EIG: [0.83333333 0.16666667 0.        ]
SY's EIG: [0.83333333 0.16666667 0.        ]

WK's EIG: [0.29079207 0.41841585 0.29079207]
SY's EIG: [0.29079207 0.41841585 0.29079207]

WK's EIG: [0.41002372 0.58997628 0.        ]
SY's EIG: [0.41002372 0.58997628 0.        ]

WK's EIG: [0.41002372 0.58997628 0.        ]
SY's EIG: [0.41002372 0.58997628 0.        ]

WK's EIG: [0. 1. 0.]
SY's EIG: [0. 1. 0.]

WK's EIG: [0.5 0.  0.5]
SY's EIG: [0.5 0.  0.5]

WK's EIG: [0.30197756 0.30197756 0.39604488]
SY's EIG: [0.30197756 0.30197756 0.39604488]

WK's EIG: [0.28571429 0.35714286 0.35714286]
SY's EIG: [0.28571429 0.35714286 0.35714286]

WK's EIG: [0.39604488 0.30197756 0.30197756]
SY's EIG: [0.39604488 0.30197756 0.30197756]

WK's EIG: [1. 0. 0.]
SY's EIG: [1.00000000e+00 0.00000000e+00 2.00214156e-16]

WK'

/Users/CoDaS/Dropbox/ShaftoLab/is-it-optimal/util.py:19: RuntimeWarning: divide by zero encountered in log
  return -np.nansum(vec*np.log(vec))
/Users/CoDaS/Dropbox/ShaftoLab/is-it-optimal/util.py:19: RuntimeWarning: invalid value encountered in multiply
  return -np.nansum(vec*np.log(vec))


WK's EIG: [0.5673813 0.4326187 0.       ]
SY's EIG: [0.5673813 0.4326187 0.       ]

WK's EIG: [0.4326187 0.5673813 0.       ]
SY's EIG: [0.4326187 0.5673813 0.       ]

WK's EIG: [1. 0. 0.]
SY's EIG: [1.00000000e+00 2.62581734e-16 0.00000000e+00]

WK's EIG: [0.33333333 0.33333333 0.33333333]
SY's EIG: [0.33333333 0.33333333 0.33333333]

WK's EIG: [0.33333333 0.33333333 0.33333333]
SY's EIG: [0.33333333 0.33333333 0.33333333]



In [102]:
# Check that WK's and SY's self-teaching is the same
for space in active_graph_space:
    stg = GraphSelfTeacher(space)
    stg.update_learner_posterior()
    print("WK's self-teaching score: {}".format(stg.update_self_teaching_posterior()))
    lik = wk2sy_full_prob(stg.likelihood())
    # print(lik.shape)
    prior = np.array([0.5, 0.5])
    st_score = self_teach(lik, prior)
    print("SY's self-teaching score: {}".format(st_score))
    print("")

WK's self-teaching score: [0.44444444 0.44444444 0.11111111]
SY's self-teaching score: [0.44444444 0.44444444 0.11111111]

WK's self-teaching score: [0.26559866 0.46880268 0.26559866]
SY's self-teaching score: [0.26559866 0.46880268 0.26559866]

WK's self-teaching score: [0.36363636 0.51048951 0.12587413]
SY's self-teaching score: [0.36363636 0.51048951 0.12587413]

WK's self-teaching score: [0.28571429 0.57142857 0.14285714]
SY's self-teaching score: [0.28571429 0.57142857 0.14285714]

WK's self-teaching score: [0.34079466 0.43482858 0.22437675]
SY's self-teaching score: [0.34079466 0.43482858 0.22437675]

WK's self-teaching score: [0.31725914 0.53043416 0.1523067 ]
SY's self-teaching score: [0.31725914 0.53043416 0.1523067 ]

WK's self-teaching score: [0.31725914 0.53043416 0.1523067 ]
SY's self-teaching score: [0.31725914 0.53043416 0.1523067 ]

WK's self-teaching score: [0.16875 0.6625  0.16875]
SY's self-teaching score: [0.16875 0.6625  0.16875]

WK's self-teaching score: [0.56818